services:
  # MariaDB 資料庫服務
  mariadb:
    image: mariadb:10.6
    container_name: free_youtube_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-secret}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-free_youtube}
      MYSQL_USER: ${MYSQL_USER:-app_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-app_password}
      TZ: Asia/Taipei
    ports:
      - "${MYSQL_PORT:-3307}:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Frontend 服務
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: free_youtube_frontend
    ports:
      - "${FRONTEND_PORT:-80}:80"
    networks:
      - app_network
    depends_on:
      - backend
    restart: unless-stopped

  # Backend API 服務
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: free_youtube_backend
    ports:
      - "${BACKEND_PORT:-8080}:8000"
    volumes:
      - ./backend:/var/www/html
    environment:
      CI_ENVIRONMENT: development
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-secret}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-free_youtube}
      MYSQL_USER: ${MYSQL_USER:-app_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-app_password}
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - app_network

  # phpMyAdmin 資料庫管理工具
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: free_youtube_phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD:-secret}
      UPLOAD_LIMIT: 100M
      MEMORY_LIMIT: 512M
      MAX_EXECUTION_TIME: 600
    ports:
      - "${PHPMYADMIN_PORT:-8081}:80"
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - app_network
    restart: unless-stopped

volumes:
  mariadb_data:
    driver: local

networks:
  app_network:
    driver: bridge
