#!/usr/bin/env php
<?php

/*
 * --------------------------------------------------------------------
 * CodeIgniter command-line tools
 * --------------------------------------------------------------------
 * The main entry point into the CLI system and allows you to run
 * commands and perform maintenance on your application.
 */

// Refuse to run when called from php-cgi
if (strpos(PHP_SAPI, 'cgi') === 0) {
    exit("The CLI tool is not supported when running php-cgi. It needs php-cli to function!\n\n");
}

// Path to the front controller (public directory)
define('FCPATH', __DIR__ . DIRECTORY_SEPARATOR . 'public' . DIRECTORY_SEPARATOR);

// Ensure the current directory is pointing to the front controller's directory
chdir(FCPATH);

/*
 *---------------------------------------------------------------
 * BOOTSTRAP THE APPLICATION
 *---------------------------------------------------------------
 */

// Load our paths config file
require FCPATH . '../app/Config/Paths.php';

$paths = new Config\Paths();

// Location of the autoloader
$autoloader = $paths->systemDirectory . '/../autoload.php';
if (!file_exists($autoloader)) {
    $autoloader = $paths->systemDirectory . '/../../autoload.php';
}
require realpath($autoloader) ?: $autoloader;

// Load environment settings
require_once $paths->systemDirectory . '/Config/DotEnv.php';
(new CodeIgniter\Config\DotEnv($paths->appDirectory . '/../'))->load();

// Define ENVIRONMENT
if (!defined('ENVIRONMENT')) {
    define('ENVIRONMENT', env('CI_ENVIRONMENT', 'production'));
}

// Load path constants
$pathsConfig = $paths->systemDirectory . '/Config/Paths.php';
require realpath($pathsConfig) ?: $pathsConfig;

// Load common functions
$common = $paths->systemDirectory . '/Common.php';
require_once realpath($common) ?: $common;

/*
 *---------------------------------------------------------------
 * GRAB OUR CODEIGNITER INSTANCE
 *---------------------------------------------------------------
 */

$app = Config\Services::codeigniter();
$app->initialize();
$app->setContext('php-cli');

/*
 *---------------------------------------------------------------
 * LAUNCH THE APPLICATION
 *---------------------------------------------------------------
 */

$app->run();
